version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  uploader:
      build:
        context: .
        dockerfile: Dockerfile
      depends_on:
        - postgres
      volumes:
        - ./:/app
      environment:
        - PYTHONUNBUFFERED=1
      env_file:
        - .env

volumes:
  postgres_data:
