version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  uploader:
      build:
        context: .
        dockerfile: Dockerfile
      depends_on:
        - postgres
      volumes:
        - ./:/app
      environment:
        - PYTHONUNBUFFERED=1

volumes:
  postgres_data:
